export interface Warehouse{

}

export interface WarehouseQueryCount{
    accept?:string;
    format?:string;
    cache?:boolean;
    taxonID?:Array<string>;
    target?: Array<any>;
    includeNonValidTaxa?:boolean;
    informalTaxonGroupId?:Array<any>;
    redListStatusId?:Array<any>
    administrativeStatusId?:Array<any>;
    finnish?:boolean;
    invasive?:boolean;
    taxonRankId?:Array<any>;
    countryId?:Array<any>;
    finnishMunicipalityId?:Array<any>;
    biogeographicalProvinceId?:Array<any>;
    area?:Array<any>;
    time?:Array<any>;
    dayOfYear?:Array<any>;
    season?:Array<any>;
    keyword?:Array<any>;
    collectionId?:Array<any>;
    reliabilityOfCollection?:Array<any>
    sourceId?:Array<string>;
    recordBasis?:Array<string>;
    superRecordBasis?:Array<string>;
    lifeStage?:Array<string>;
    sex?:Array<string>;
    invasiveControl?:Array<string>;
    invasiveControlled?:Array<string>;
    documentID?:Array<any>;
    unitId?:Array<any>;
    individualId?:Array<any>;
    individualCountMin?:number;
    individualCountMax?:number;
    loadedLaterThan?:Date;
    loadedBefore?:Date;
    firstLoadedLaterThan?:Date;
    coordinates?: Array<any>;
    coordinateAccuracyMax?:number;
    ykj1km?:Array<any>;
    ykj10km?:Array<any>;
    ykj50km?:Array<any>;
    ykj100km?:Array<any>;
    ykj1kmCenter?:Array<any>;
    ykj10kmCenter?:Array<any>;
    ykj50kmCenter?:Array<any>;
    ykj100kmCenter?:Array<any>;
    typeSpecimen?:boolean;
    nativeOccurrence?:boolean;
    hasDocumentMedia?:boolean;
    hasGatheringMedia?:boolean;
    hasUnitMedia?:boolean;
    hasMedia?:boolean;
    editorId?:Array<any>;
    editorOrObserverId?:Array<any>;
    observerId?:Array<any>;
    secureReason:Array<string>;
    secureLevel:Array<string>;
    secured:boolean;
    annotated:boolean;
    annotationType:Array<any>;
    annotatedBefore:Date;
    includeSystemAnnotations:boolean;
    annotatedLaterThan:Date;
    qualityIssues:undefined;
    reliable:boolean;
    taxonReliability:Array<string>;
    unidentified:boolean;
    originalTaxonId:Array<any>;
    taxonCensus:Array<any>;
    originalTarget:Array<any>;
    firstLoadedBefore:Array<any>
    editorPersonToken:string;
    observerPersonToken:string;
    editorOrObserverPersonToken:string;
}

export interface WarehouseQueryList {
  includeNonValidTaxa?: boolean;
  taxonId?: Array<string>;
  target?: Array<string>;
  taxonRankId?: string;
  informalTaxonGroupId?: Array<string>;
  administrativeStatusId?: Array<string>;
  redListStatusId?: Array<string>;
  finnish?: boolean;
  invasive?: boolean;
  countryId?: Array<string>;
  finnishMunicipalityId?: Array<string>;
  biogeographicalProvinceId?: Array<string>;
  area?: Array<string>;
  time?: Array<string>;
  dayOfYearBegin?: number;
  dayOfYearEnd?: number;
  keyword?: Array<string>;
  collectionId?: Array<string>;
  coordinateAccuracyMax?: number;
  sourceId?: Array<string>;
  superRecordBasis?: Array<string>;
  recordBasis?: Array<string>;
  lifeStage?: Array<string>;
  taxonReliability?: Array<string>;
  sex?: Array<string>;
  documentId?: Array<string>;
  unitId?: Array<string>;
  individualId?: Array<string>;
  individualCountMin?: number;
  individualCountMax?: number;
  loadedLaterThan?: Date;
  coordinates?: Array<string>;
  typeSpecimen?: boolean;
  hasDocumentMedia?: boolean;
  hasGatheringMedia?: boolean;
  hasUnitMedia?: boolean;
  hasMedia?: boolean;
  secureReason?: Array<string>;
  editorId?: Array<string>;
  secured?: boolean;
  ykj10km?: string;
  ykj10kmCenter?: string;
  unidentified?: boolean;
  cache?: boolean;
  reliable?: boolean;
  observerPersonToken?: string;
  editorPersonToken?: string;
  editorOrObserverPersonToken?: string;
  qualityIssues?: string;
  annotationType?: Array<string>;
  annotatedBefore?: Date;
  annotatedLaterThan?: Date;
}